load("@aspect_rules_js//js:defs.bzl", "js_test")

js_test(
    name = "main_test",
    args = [
        "$(location //src/nodejson:rendezqueue_nodejson)",
        "$(location //src/webchat:index_html)",
        "$(location //src/webchat:script_js_file)",
        "$(location //src:rendezqueue_client_js_file)",
    ],
    data = [
        "//:node_modules",
        "//src:rendezqueue_client_js_file",
        "//src/nodejson:rendezqueue_nodejson",
        "//src/webchat:index_html",
        "//src/webchat:script_js_file",
        "@playwright//:chromium-headless-shell",
    ],
    entry_point = "main_test.js",
    env = {
        "PLAYWRIGHT_BROWSERS_PATH": "$(rootpath @playwright//:chromium-headless-shell)/../",
        "NODE_PATH": "node_modules",
    },
)
