syntax = "proto3";
package rendezqueue;

message TrySwapRequest {
  uint32 b64 = 1;
  uint32 ttl = 2;
  bytes key = 4;
  bytes sid = 5;
  uint32 offset = 6;
  repeated bytes values = 7;
}

message TrySwapResponse {
  // Bitfield that specifies whether key, sid, and values are base64url-encoded
  // using the 0x4, 0x2, and 0x1 bits respectively.
  uint32 b64 = 1;
  // Remaining seconds.
  uint32 ttl = 2;
  // Your key. Just to confirm. Can be ignored.
  bytes key = 4;
  // Your sid. Just to confirm. Can be ignored.
  bytes sid = 5;
  // Holds number of values (when values is not returned).
  uint32 offset = 6;
  // Other party's values.
  repeated bytes values = 7;
}

service RendezqueueService {
  rpc TrySwap (TrySwapRequest) returns (TrySwapResponse) {}
}
