load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library")

js_library(
    name = "swapstore_js",
    srcs = ["swapstore.js"],
    visibility = ["//test:__subpackages__"],
)

js_library(
    name = "rendezqueue_json_impl_js",
    srcs = ["rendezqueue_json_impl.js"],
    visibility = ["//test:__subpackages__"],
    deps = ["swapstore_js"],
)

js_binary(
    name = "rendezqueue_nodejson",
    data = [
        ":main.js",
        ":rendezqueue_json_impl_js",
    ],
    entry_point = ":main.js",
)

sh_binary(
    name = "some_requests_sh",
    srcs = [
        "some_requests.sh",
    ],
)
