load("@aspect_rules_js//js:defs.bzl", "js_test")
load("@fildesh//tool/bazel:fildesh_run.bzl", "fildesh_run")

fildesh_run(
    name = "package_json",
    testonly = True,
    output_by_xof = {"o": "package.json"},
    src_content = """
|< splice -- / "(type module)" /
|- sxpb2json
|> splice -o $(XOF o)
""",
)

js_test(
    name = "bytestring_test",
    size = "small",
    data = [
        "bytestring_test.js",
        ":package_json",
    ],
    entry_point = "bytestring_test.js",
)

js_test(
    name = "client_test",
    size = "small",
    args = [
        "$(location //src/nodejson:rendezqueue_nodejson)",
    ],
    data = [
        ":package_json",
        "//src:rendezqueue_client_js_file",
        "//src/nodejson:rendezqueue_nodejson",
    ],
    entry_point = "client_test.js",
)

js_test(
    name = "main_test",
    size = "small",
    data = [
        "main_test.js",
        ":package_json",
        "//src/nodejson:main_js",
        "//test/scenario:webchat.json",
    ],
    entry_point = "main_test.js",
)

js_test(
    name = "swapstore_test",
    size = "small",
    data = [
        "swapstore_test.js",
        ":package_json",
        "//src/nodejson:swapstore_js",
    ],
    entry_point = "swapstore_test.js",
)

js_test(
    name = "tryswap_concat_test",
    size = "small",
    data = [
        "tryswap_concat_test.js",
        ":package_json",
        "//src/nodejson:swapstore_js",
    ],
    entry_point = "tryswap_concat_test.js",
)
