load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_test")

js_test(
    name = "bytestring_test",
    size = "small",
    data = [
        "bytestring_test.js",
    ],
    entry_point = "bytestring_test.js",
)

js_test(
    name = "main_test",
    size = "small",
    data = [
        "main_test.js",
        "//src/nodejson:main_js",
        "//test/scenario:webchat.json",
    ],
    entry_point = "main_test.js",
)

js_test(
    name = "swapstore_test",
    size = "small",
    data = [
        "swapstore_test.js",
        "//src/nodejson:swapstore_js",
    ],
    entry_point = "swapstore_test.js",
)

js_test(
    name = "tryswap_concat_test",
    size = "small",
    data = [
        "tryswap_concat_test.js",
        "//src/nodejson:swapstore_js",
    ],
    entry_point = "tryswap_concat_test.js",
)
